site_name: Kaleo's Headspace
site_author: Kaleo
site_description: Kaleo's personal website, where you can find his notes, projects and blogs.

theme: 
  name: material
  palette:
    primary: amber
    scheme: slate
  features:
    - navigation.top
    - navigation.tabs
    - navigation.path
    - navigation.expand
    - navigation.indexes
    - navigation.instant

extra:
  social: # show GitHub, Twitter & Email at footage
    - icon: fontawesome/brands/github
      link: https://github.com/Kaleo996
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kaleo996
    - icon: fontawesome/solid/envelope
      link: mailto:yihangchen2003@gmail.com
  analytics:
    provider: google
    property: G-5D9MVMM08N

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

plugins:
  - blog:
      post_url_format: "{slug}"
  # - optimize

extra_javascript: # KaTeX
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

nav:
  - Home:
    - index.md
    - About Me: home/about_me.md
    - Friends: home/friends.md
  - EECS:
    - eecs/index.md
    - ZJU C Programming: eecs/clang/index.md
    - ZJU Discrete Math: https://www.yuque.com/linguisty/zju_courses/discrete
    - ZJU Software Engineering: eecs/se.md
    - Music Processing Analysis:
      - eecs/mpa/index.md
      - 1 Representation: eecs/mpa/1_represent.md
      - 4 Music Synchronization: eecs/mpa/4_sync.md
      - 5 Music Structure: eecs/mpa/5_struct.md
    - 'GCT634: Musical Applications of Machine Learning':
      - eecs/gct634/index.md
      - W2-4 Music Classification:
        - eecs/gct634/w2-4_classify/index.md
        - 'Ref: DeepMIR Lec3. Timbre & Acoustic Features': eecs/gct634/w2-4_classify/deepmir3.md
      - W5 Music Recommandation & Retrieval: eecs/gct634/w5_recommend.md
      - W7-10 Music Transcription: eecs/gct634/w7-10_transcript/index.md
  - Linguistics:
    - ling/index.md
    - Middle Chinese Pronunciation:
      - ling/mid_ch/index.md
      - Onset: ling/mid_ch/onset.md
      - Tone & Coda: ling/mid_ch/tone_coda.md
      - Rime: ling/mid_ch/rime.md
    - Hawaiian Language:
      - ling/hawaii/index.md
      - 夏威夷文 & 发音: ling/hawaii/夏威夷文&发音.md
      - 夏威夷语语法: ling/hawaii/夏威夷语语法.md
    - ZJU Syntax:
      - ling/syntax/index.md
      - Constituents & Categories: ling/syntax/constituent.md
      - PS Rules & X' Theory: ling/syntax/x_bar.md
      - Movement: ling/syntax/move.md
      - Binding: ling/syntax/bind.md
      - Universal Grammar: ling/syntax/ug.md
  - Blog:
    - blog/index.md

